name: García Maganto
favicon: null
layout_spectrum: 0.14422304509207606
typography_spectrum: 0.24559569917619228
title: Process
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.031169509049504995
  lightness: 0.8543807549867779
  saturation: 0.301783342147246
  rhythmicContrast: 0.20353137841448188
purpose: []
