name: García Maganto
favicon: null
layout_spectrum: 0.14422304509207606
typography_spectrum: 0.24559569917619228
title: Process
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
